
print("=========================================")
print("= NAMA    : Oktovan Agung Shailendra     ")
print("= NIM     : 312010131                    ")
print("= KELAS   : TI.20 A.1                    ")
print("=========================================")


print("Please enter your full name : Oktovan Agung Shailendra")
fullname=input()
print("Please enter nickname : Oktovan")
nickname=input()
print("Please enter your NiM : 312010131")
npm=input()
print("Please enter place of birth : BEKASI")
pob=input()
print("Please enter date of birth : 22")
date=input()
print("Please enter your month of birth : Oktober")
month=input()
print("Please enter year of birth : 2002")
year=input()
print("Please enter your phone number : 08995251170")
phone=input()
print("Please enter your address : Kp. Pule")
address=input()

dob=input("2020-year")

print("\n\n Assalamu'alaikum. ")
print("f\n Let me introduce my self, my name is {Oktovan Agung Shailendra}, but you can call me {Oktovan}, my NPM {312010131}, I was born in {BEKASI} and iam {18} years old, I am very glad if you want to invite my house in {Kp. Pule}, So don't forget to call me before with the number {08995251170}, \n\n Thanks you very much ")
